model_name: random_forest
artifact_path: basic_rf

tag_key: "model"
tag_value: "basic RF"

module_name: "sklearn.neural_network"
class_name: "MLPRegressor"

params:
    hidden_layer_sizes: (100, 50)
    max_iter: 500
    verbose: True

param_grid:
  hidden_layer_sizes:
    - "(50,)"
    - "(100, 50)"
    - "(150, 100, 50)"
  max_iter: [200, 500, 1000]
# hydra:
#   sweeper:
#       params:
#         +params.n_estimators: "100, 200, 500"
#         +params.criterion: "'gini', 'entropy', 'log_loss'"
#         +params.random_state: 88