model_name: mlp_regressor
artifact_path: basic_mlp

tag_key: "model"
tag_value: "basic MLP"

module_name: "sklearn.neural_network"
class_name: "MLPRegressor"

params:
  hidden_layer_sizes: [100, 50]
  max_iter: 500
  verbose: True

param_grid:
  hidden_layer_sizes:
    - (50,)
    - (100, 50)
    - (150, 100, 50)
  max_iter: [200, 500, 1000]
