defaults:
  - _self_

folds: 3

cv_evaluation_metric: "mean_test_neg_mean_squared_error"

pyfunc_predict_fn: "predict"

metrics:
  neg_mean_squared_error: neg_mean_squared_error
  r2: r2
evaluation_metric: r2

best_model_alias: champion
best_model_name: random_forest


#metrics:
#  accuracy: "accuracy"
#  f1: "f1"
#evaluation_metric: "f1"

# hydra:
#   sweeper:
#       sampler:
#         seed: 8888
#       # n_trials: 20 # number of times to try to optimize the search space
#       direction: maximize # minimize