data:
  url: https://storage.yandexcloud.net/sledobot.ru/Airbnb_Data.csv
  version: "1.1"
  message: "Add data version  1.1"

local_data:
  path: data/data.csv
  repo: .
  remote: localstore

defaults:
  - data: airbnb
  - _self_