data:
  sample_size: 0.2
  repo: /mnt/c/Users/amira/PycharmProjects/MLOps
  remote: localstore
  dataset_name: "sample.csv"

version: '1.18'
message: Add data version 1.18

defaults:
  - _self_
  - data: sample

hydra:
  run:
    dir: ../outputs
