name: Example testing

on:
  push:
    branches:
      - main
      - phase5
#    paths:
#      - 'src'
#      - 'scripts'

permissions:
  contents: read

jobs:
  test-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checking out our code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'
          cache: 'pip'

      - name: install python packages
        run: |
            python3.11 -m pip install --upgrade pip 
            pip3.11 install -r mlflow.requirements.txt 

#      - name: Run your app
#        run: python3.11 src/app.py &
#
#      - name: Export variables
#        run: |
#          echo $PWD
#          export ZENML_CONFIG_PATH=$PWD/services/zenml
#          export PROJECTPATH=$PWD
#          export AIRFLOW_HOME=$PWD/services/airflow
#          export PYTHONPATH=$PWD/src
#
#      - name: Run ZenML server
#        run: zenml down && zenml up
#
#      - name: Test with pytest
#        run: pytest tests
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: amirosik/tm5mlops

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Connect to VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLOUD_ADDRESS }}
          username: amir
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker run -d -p 5152:8080 ${{ secrets.DOCKER_USERNAME }}/tm5mlops:latest;
